services:
  metabase:
    build:
      context: .
      dockerfile: metabase/Dockerfile
    container_name: metabase
    ports:
      - "${MB_PORT:-3000}:3000"
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    volumes:
      - ./metabase-data:/metabase-data
      - ./data:/data:ro
    restart: unless-stopped
